apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: phonepay
  name: phonepay-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      run: phonepay
  template:
    metadata:
      labels:
        run: phonepay
    spec:
      containers:
      - name: cont1
        image: vdbsrao/coffee:latest
        ports:
        - containerPort: 80
        ---------------------------
apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  type: NodePort
  selector:
    app: phonepay
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
        

